development:
  adapter: postgresql
  database: webuyanystairlift_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: webuyanystairlift_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: webuyanystairlift_production
  pool: 5
  timeout: 5000